// Code generated by mockery v2.53.2. DO NOT EDIT.

package mockdi

import (
	sessionschema "test_data_flow/internal/session/schema"

	mock "github.com/stretchr/testify/mock"
)

// MockISessionRepository is an autogenerated mock type for the ISessionRepository type
type MockISessionRepository struct {
	mock.Mock
}

type MockISessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISessionRepository) EXPECT() *MockISessionRepository_Expecter {
	return &MockISessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: uid, ipAddress
func (_m *MockISessionRepository) Create(uid int64, ipAddress string) (string, error) {
	ret := _m.Called(uid, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) (string, error)); ok {
		return rf(uid, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(int64, string) string); ok {
		r0 = rf(uid, ipAddress)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(uid, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - uid int64
//   - ipAddress string
func (_e *MockISessionRepository_Expecter) Create(uid interface{}, ipAddress interface{}) *MockISessionRepository_Create_Call {
	return &MockISessionRepository_Create_Call{Call: _e.mock.On("Create", uid, ipAddress)}
}

func (_c *MockISessionRepository_Create_Call) Run(run func(uid int64, ipAddress string)) *MockISessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(string))
	})
	return _c
}

func (_c *MockISessionRepository_Create_Call) Return(_a0 string, _a1 error) *MockISessionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_Create_Call) RunAndReturn(run func(int64, string) (string, error)) *MockISessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUID provides a mock function with given fields: uid
func (_m *MockISessionRepository) DeleteByUID(uid int64) error {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISessionRepository_DeleteByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUID'
type MockISessionRepository_DeleteByUID_Call struct {
	*mock.Call
}

// DeleteByUID is a helper method to define mock.On call
//   - uid int64
func (_e *MockISessionRepository_Expecter) DeleteByUID(uid interface{}) *MockISessionRepository_DeleteByUID_Call {
	return &MockISessionRepository_DeleteByUID_Call{Call: _e.mock.On("DeleteByUID", uid)}
}

func (_c *MockISessionRepository_DeleteByUID_Call) Run(run func(uid int64)) *MockISessionRepository_DeleteByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockISessionRepository_DeleteByUID_Call) Return(_a0 error) *MockISessionRepository_DeleteByUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISessionRepository_DeleteByUID_Call) RunAndReturn(run func(int64) error) *MockISessionRepository_DeleteByUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUID provides a mock function with given fields: uid
func (_m *MockISessionRepository) GetByUID(uid int64) (*sessionschema.SessionModel, error) {
	ret := _m.Called(uid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUID")
	}

	var r0 *sessionschema.SessionModel
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*sessionschema.SessionModel, error)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(int64) *sessionschema.SessionModel); ok {
		r0 = rf(uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessionschema.SessionModel)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockISessionRepository_GetByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUID'
type MockISessionRepository_GetByUID_Call struct {
	*mock.Call
}

// GetByUID is a helper method to define mock.On call
//   - uid int64
func (_e *MockISessionRepository_Expecter) GetByUID(uid interface{}) *MockISessionRepository_GetByUID_Call {
	return &MockISessionRepository_GetByUID_Call{Call: _e.mock.On("GetByUID", uid)}
}

func (_c *MockISessionRepository_GetByUID_Call) Run(run func(uid int64)) *MockISessionRepository_GetByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockISessionRepository_GetByUID_Call) Return(_a0 *sessionschema.SessionModel, _a1 error) *MockISessionRepository_GetByUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockISessionRepository_GetByUID_Call) RunAndReturn(run func(int64) (*sessionschema.SessionModel, error)) *MockISessionRepository_GetByUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISessionRepository creates a new instance of MockISessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISessionRepository {
	mock := &MockISessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
